### ISSUE TITLE
Error thrown with Anki 2.1.21 beta 2

### ISSUE THREAD

**Issue by Cupbox** [ijgnd/anki__copy_current_note_contents_to_add_window#3]
Debug info:
Anki 2.1.21 (65ec9d19) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-02-25 07:37:01

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 444, in handler
  File "aqt\editor.py", line 443, in <lambda>
  File "C:\Users\John Smith\AppData\Roaming\Anki2\addons21\759018284\copycurrent.py", line 67, in _on_open_in_add_window
    open_in_add_window(editor.note, did)
  File "C:\Users\John Smith\AppData\Roaming\Anki2\addons21\759018284\copycurrent.py", line 44, in open_in_add_window
    addedCardWindow.deckChooser.setDeckName(deckname)
AttributeError: 'NoneType' object has no attribute 'deckChooser'

**Comment by Cupbox** [comment]
Working as of beta 3.

**Comment by ijgnd** [comment]
General note: Thanks for spotting and reporting problems early and in this case quickly notifying me that it has been solved. I'm glad that I can strike this from my todo list.
